# Generated by Django 5.1.1 on 2024-11-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
