# Generated by Django 5.1.1 on 2024-11-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_arrival_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='anon_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='extension_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sharing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
