# Generated by Django 5.1.1 on 2024-11-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_anon_time_event_extension_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='sharing_time',
            new_name='timeliness',
        ),
    ]
