# Generated by Django 5.1.1 on 2024-12-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_rename_sharing_time_event_timeliness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='anon_time',
        ),
    ]
