# Generated by Django 5.1.1 on 2024-12-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_event_anon_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='anon_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
