# Generated by Django 5.1.1 on 2024-12-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_remove_event_extension_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='extension_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
