# Generated by Django 5.1.1 on 2024-12-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_event_extension_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='timeliness',
        ),
    ]
