# Generated by Django 5.1.1 on 2024-12-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_remove_event_timeliness'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timeliness',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
