# Generated by Django 5.1.1 on 2024-12-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_event_timeliness'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sharing_speed',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
