# Generated by Django 5.1.1 on 2025-03-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_event_sharing_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
