# Generated by Django 5.1.1 on 2025-03-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_eventsharelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsharelog',
            name='shared_at',
            field=models.DateTimeField(),
        ),
    ]
