# Generated by Django 5.1.1 on 2025-03-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_alter_eventsharelog_shared_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsharelog',
            options={},
        ),
    ]
