# Generated by Django 5.1.1 on 2025-04-17 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_alter_eventsharelog_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsharelog',
            options={'ordering': ['-shared_at'], 'verbose_name': 'Event Share Log', 'verbose_name_plural': 'Event Share Logs'},
        ),
        migrations.AddField(
            model_name='eventsharelog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsharelog',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventsharelog',
            name='shared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
