# Generated by Django 5.1.1 on 2025-04-17 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_alter_eventsharelog_options_eventsharelog_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsharelog',
            options={},
        ),
        migrations.RemoveField(
            model_name='eventsharelog',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='eventsharelog',
            name='deleted_by',
        ),
        migrations.AlterField(
            model_name='eventsharelog',
            name='shared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
