# Generated by Django 5.1.1 on 2025-05-20 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0007_alter_organization_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MISPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=255)),
                ('apikey', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misp_servers', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'MISP Server',
                'verbose_name_plural': 'MISP Servers',
            },
        ),
    ]
