# Generated by Django 5.1.1 on 2025-07-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misp_servers', '0001_initial'),
        ('organizations', '0007_alter_organization_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mispserver',
            name='organization',
        ),
        migrations.AddField(
            model_name='mispserver',
            name='organizations',
            field=models.ManyToManyField(related_name='misp_servers', to='organizations.organization'),
        ),
    ]
