# Generated by Django 5.1.1 on 2024-11-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_key', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publickey',
            name='value',
        ),
        migrations.AddField(
            model_name='publickey',
            name='file',
            field=models.FileField(default=1, upload_to='public_keys/'),
            preserve_default=False,
        ),
    ]
