# Generated by Django 5.1.1 on 2025-05-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_files', '0003_alter_eventattachment_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattachment',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
