# Generated by Django 5.1.1 on 2024-11-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='external_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
