# Generated by Django 5.1.1 on 2024-11-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
