# Generated by Django 5.1.1 on 2024-11-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='prefix',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
