# Generated by Django 5.1.1 on 2024-12-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='external_id',
            field=models.CharField(max_length=100),
        ),
    ]
