# Generated by Django 5.1.1 on 2026-07-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_alter_organization_external_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "annex",
                    models.CharField(
                        choices=[
                            ("essential", "Essential (Annex I)"),
                            ("important", "Important (Annex II)"),
                        ],
                        default="essential",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["annex", "name"],
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="sectors",
            field=models.ManyToManyField(
                blank=True, related_name="organizations", to="organizations.sector"
            ),
        ),
    ]
