# Generated by Django 5.1.1 on 2025-05-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('api_key', models.CharField(max_length=500)),
                ('base_url', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPReputationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('is_malicious', models.BooleanField(default=None, null=True)),
                ('threat_score', models.FloatField(default=0)),
                ('confidence_score', models.FloatField(default=0)),
                ('reported_by', models.JSONField(default=dict)),
                ('details', models.JSONField(default=dict)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address'], name='ip_reputati_ip_addr_2f2722_idx'), models.Index(fields=['is_malicious'], name='ip_reputati_is_mali_30de16_idx')],
            },
        ),
    ]
