# Generated by Django 5.1.1 on 2025-06-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        ('organizations', '0007_alter_organization_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='organization',
        ),
        migrations.AddField(
            model_name='form',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='forms', to='organizations.organization'),
        ),
    ]
