# Generated by Django 5.1.1 on 2025-05-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_organization_external_id'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='strategies', to='organizations.organization'),
        ),
    ]
