# Generated by Django 5.1.1 on 2025-06-24 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0019_eventsharelog_deleted_at_eventsharelog_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('prompt', models.TextField(help_text='User prompt for report generation')),
                ('generated_content', models.TextField(help_text='AI-generated report content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tokens_used', models.IntegerField(blank=True, help_text='Number of tokens used for generation', null=True)),
                ('generation_time', models.FloatField(blank=True, help_text='Time taken for generation in seconds', null=True)),
                ('events', models.ManyToManyField(help_text='Events analyzed in this report', related_name='reports', to='event.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
