# Generated by Django 5.1.1 on 2025-07-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='llm_model',
            field=models.CharField(blank=True, help_text="LLM model used for generation (e.g., 'gemini-1.5-flash', 'llama3.1:8b')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='llm_provider',
            field=models.CharField(blank=True, help_text="LLM provider used for generation (e.g., 'gemini', 'ollama')", max_length=50, null=True),
        ),
    ]
