# Generated by Django 5.1.1 on 2026-07-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_report_llm_model_report_llm_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="gemini",
                        help_text="Active LLM provider: 'gemini' or 'ollama'",
                        max_length=50,
                    ),
                ),
                (
                    "ollama_model",
                    models.CharField(
                        default="llama3.1:8b",
                        help_text="Model used when provider is 'ollama'",
                        max_length=100,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LLM configuration",
                "verbose_name_plural": "LLM configuration",
            },
        ),
        migrations.AddField(
            model_name="report",
            name="error_message",
            field=models.TextField(
                blank=True, help_text="Error details when generation failed", null=True
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generating", "Generating"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Lifecycle status of the async report generation",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="generated_content",
            field=models.TextField(
                blank=True, default="", help_text="AI-generated report content"
            ),
        ),
    ]
